/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppChangePasswordRouteImport } from './routes/app.change-password'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/app/change-password',
  path: '/app/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super': typeof SuperRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super': typeof SuperRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super': typeof SuperRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/super'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/requests'
    | '/app/change-password'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/super'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/requests'
    | '/app/change-password'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/super'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/requests'
    | '/app/change-password'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SuperRoute: typeof SuperRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/change-password': {
      id: '/app/change-password'
      path: '/app/change-password'
      fullPath: '/app/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SuperRoute: SuperRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AppChangePasswordRoute: AppChangePasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
